services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://tenngage:2531@postgres:5432/crm-service
      - CELERY_BROKER_URL=amqp://tenngage:2531@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - rabbitmq
    volumes:
      - .:/app  # для разработки - монтируем код
    command: fastapi dev src/api/main.py --host 0.0.0.0 --port 8000

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=crm-service
      - POSTGRES_USER=tenngage
      - POSTGRES_PASSWORD=2531
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management
    ports: 
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=tenngage
      - RABBITMQ_DEFAULT_PASS=2531

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://tenngage:2531@rabbitmq:5672//
      - CELERY_BACKEND_URL=rpc://
    command: celery -A src.tasks.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
